
title: Stockholm Data Science Forum Seminars
description: An inter-disciplincary data science community

# Build settings
markdown: kramdown
github: [metadata]
encoding: UTF-8
kramdown:
input: GFM
hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end
theme: jekyll-theme-slate
plugins:
  - jekyll-feed




# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

